# Generated by Django 5.0.4 on 2024-04-25 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.PositiveIntegerField(default=0, verbose_name='Minimal payment for work')),
                ('experience', models.CharField(default='No experience', max_length=50, verbose_name='Work experience')),
                ('ownership_form', models.CharField(default='Legal entity', max_length=50, verbose_name='Ownership form')),
                ('about_as', models.TextField(max_length=1000, verbose_name='About me')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profiles/customer_logo', verbose_name='Photo of company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_of_work', models.PositiveIntegerField(default=0, verbose_name='The cost of work')),
                ('experience', models.CharField(default='No experience', max_length=50, verbose_name='Work experience')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='Contact phone')),
                ('ownership_form', models.CharField(default='Natural person', max_length=50, verbose_name='Ownership form')),
                ('payment_method', models.CharField(default='Paypal', max_length=50, verbose_name='Payment method')),
                ('about_me', models.TextField(max_length=1000, verbose_name='About me')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='profiles/portfolio', verbose_name='Professional portfolio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/freelancers_photo', verbose_name='Photo of freelancer')),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_from', to='profiles.customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelancer',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_from', to='profiles.freelancer'),
        ),
    ]
