# Generated by Django 5.0.4 on 2024-04-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='about_as',
            new_name='about_us',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='reviews',
        ),
    ]
