# Generated by Django 5.0.4 on 2024-04-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_phone',
            field=models.CharField(default='+7...', max_length=15, verbose_name='Contact phone'),
        ),
    ]
